# https://taskfile.dev

version: '3'

vars:

tasks:
  run:
    uvicorn server:app --reload --host 0.0.0.0 --port 8000
  inspect-mcp:
    npx @modelcontextprotocol/inspector uv run python -m src.services.calendar_service.mcp
